#!/bin/bash
# CONFIG
DHOST=deflect.ca

#set -e

if [ $# -ne 1 ]; then	
   echo "Need a hostname to mount the encfs on"
   exit 1
fi
echo ${1}.${DHOST}
host=${1}.${DHOST}

[ -z "$SSH_AUTH_SOCK" ] && eval `ssh-agent` && OUR_AGENT=$SSH_AGENT_PID
ssh-add -ls 2>&1| grep `ssh-keygen -lf /usr/local/deflect/etc/edge_id | awk '{print $2}'` >/dev/null || ssh-add /usr/local/deflect/etc/edge_id

ssh $host grep /usr/local/trafficserver /proc/mounts 
if [ $? -ne 0 ]; then
  source /usr/local/deflect/scripts/encfs_pass2
  echo "mounting on host $host"
  /usr/local/deflect/scripts/init-enc.exp $host $ENCFS_PASS /usr/local/.trafficserver/ /usr/local/trafficserver/
  sleep 1
  ssh $host "service trafficserver restart ; service log-courier restart"
else
  echo "/usr/local/trafficserver already mounted"
fi

[ -n "$OUR_AGENT" ] && kill $OUR_AGENT
