---
- hosts: controller
  gather_facts: no

  vars_prompt:
    - name: 'default_dnet'
      prompt: 'Name of the default dnet '
      default: 'default'
      private: no

    - name: 'default_dnet_domain'
      prompt: 'Name of the default dnet domain'
      default: 'deflect.ca'
      private: no

    - name: 'dnet_list'
      prompt: 'List other dnets names, comma separated with no spaces. Space for none'
      default: 'staging,redzone'
      private: no

    - name: 'swabber_grace'
      prompt: 'Swabber grace'
      default: '300'
      private: no

    - name: 'le_url'
      prompt: 'Letsencrypt server host:port'
      default: 'le.deflect.ca:1111'
      private: no

    - name: 'dash_clients_yml'
      prompt: 'Path to clients.yml on Dashboard'
      default: '/var/www/brainsconfig/site.yml'
      private: no

    - name: 'tls_bundle_path'
      prompt: 'Path to tls bundles on Dashboard'
      default: '/var/www/brainsconfig/tls_bundles'
      private: no

    - name: 'email_notify'
      prompt: 'Your email address to get notifications'
      default: 'notify@example.local'
      private: no

    - name: 'email_key_id'
      prompt: 'Your email address to use with gpg'
      default: 'notify@example.local'
      private: no

    - name: 'le_email'
      prompt: 'Your email address to use for LetsEncrypt'
      default: 'letsencrypt@example.local'
      private: no

    - name: 'authoritative_nameserver_grep_init'
      prompt: 'Authoritive name servers to grep for. Comma separated with not spaces'
      default: 'deflect,someplaceelse'
      private: no

    - name: 'edgemanage_transfer_ip'
      prompt: 'IP addresses of DNS service for transfers. Comma separated with no spaces. Space for none'
      default: ' '
      private: no

  roles:
    - {role: init, tags: init}
    - {role: autobrains_update}
